yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG: 
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

yatube/posts/models.py
from django.contrib.auth import get_user_model

from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста',)
    pub_date = models.DateTimeField(verbose_name='Дата публикации',
                                    auto_now_add=True,)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )

    def __str__(self):
        return self.text[:15]

    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост, к которому крепится комментарий',
        help_text='Укажите пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        help_text='Введите Автора',
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст'
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
        help_text='Укажите подписчика'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
        help_text='Укажите автора'
    )

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=('user', 'author'), name='follow_unique'),
        )
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return self.user.username, self.author.username

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["text", "group", "image"]
        labels = {"text": "Введите текст",
                  "group": "Выберите группу",
                  "image": "Вставьте свою картинку"}
        help_texts = {"text": "Удивите всех своей историей",
                      "group": "Это всё ...",
                      "image": "Картинка должна быть здесь"}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Напишите комментарий',
        }

yatube/posts/views.py
from .utils import page_context
from django.conf import settings

from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, Follow
from django.core.paginator import Paginator


def pagination(request, posts):
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return(page_obj)


@cache_page(20)
def index(request):
    post_list = Post.objects.select_related().all()
    paginator = Paginator(post_list, settings.PAGINATOR_POST_COUNT)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    index = True
    context = {
        'page_obj': page_obj,
        'index': index,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = page_context(request, group.posts.all())
    context.update(group=group)
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = pagination(request, posts)
    following = (request.user.is_authenticated
                 and request.user != author
                 and Follow.objects.filter(
                     user=request.user,
                     author=author).exists())
    context = {
        'page_obj': page_obj,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    form = CommentForm(request.POST or None)
    author = post.author
    post_count = author.posts.count()
    context = {
        'title': f'Пост {post.text[:30]}',
        'post': post,
        'post_count': post_count,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        author = request.user
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = author
            new_post.save()
            return redirect('posts:profile', author.username)
        return render(request, 'posts/create_post.html',
                      {'is_edit': True, 'form': form})
    form = PostForm()
    return render(request, 'posts/create_post.html',
                  {'is_edit': True, 'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    # Получите пост
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.select_related('group').filter(
        author__following__user=request.user)
    context = page_context(request, posts)
    context.update(posts=posts)
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', author)


@login_required
def profile_unfollow(request, username):
    Follow.objects.filter(
        user=request.user, author__username=username
    ).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %}Редактирование поста{% else %}Создание поста{% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card-header">
          {% if is_edit %}Редактирование поста{% else %}Новый пост{% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
              <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-riht">{{ field.label }}{% if field.field.required %}<span class="required text-danger">*</span>{% endif %}</label>
                <div class="col-md-6">
                  {{ field }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              {% for error in form.errors %}
                <div class="alert alert-danger" role="alert">
                  {{ error|escape }}
                </div>
              {% endfor %}
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}Сохранить{% else %}Добавить{% endif %}   
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title%}
Публикации избранных авторов
{% endblock title %}
{% block content %}
<div class="container">
  <h1> Публикации избранных авторов </h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
        <a href="{% url 'posts:profile' post.author %}"> все посты пользователя </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <p><a href="{% url 'posts:post_detail' post.id %}">подробная информация</a></p>
    {% if post.group %}
      <p><a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a></p>
    {% endif %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
  Посты сообщества {{ group.title }}
{% endblock%}  
{% block content %}
  <div class="container py-5">     
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post  in page_obj %}
      <article>
        {% include 'posts/includes/article.html' %}
      </article>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr| truncatewords:30 }}</p>
       <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}Главная страница{% endblock %}      
{% block content %} 
<div class="container py-5">     
  <h1>Последние обновления на сайте</h1>
  {% for post  in page_obj %}  
      {% include 'posts/includes/article.html' %}
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    {% if post.group.slug %}
    <p>
      <a href="{% url 'posts:group_posts' post.group.slug %}">Все посты группы</a>
    </p> 
    {% endif %}  
    {% if not forloop.last %}<hr>{% endif %}
      </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index3.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
<div class="container">
  <h1> Последние обновления на сайте </h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      <li>
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      </p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    {% if post.group %}  
    <p>
      <a href="{% url 'posts:grouplist' post.group.slug %}">все записи группы</a>
    </p>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor%}
  {% include 'includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.created|date:"j E Y" }}
        </li>
        {% if post.group %}
            
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url "posts:group_posts" post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-ontent-between align-items-center">
          Всего постов автора:  <span>{{ post_count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url "posts:profile" post.author %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img src="{{ im.url }}">
      {% endthumbnail %}
      <p>
      {{ post.text }}
      </p>
      {% if post.author == request.user %}
        <a href="{% url "posts:post_edit" post.id %}"
        class="btn btn-primary"
        >
          Редактировать запись
        </a>
      {% endif %}
      {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url "posts:add_comment" post.id %}">
            {% csrf_token %}
              <div class="form-group mb-2">
                {{ form.text|addclass:"form-control" }}
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
      {% endif %}
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body">
            <h5 class="mt-0">
              <a 
              href="{% url "posts:profile" comment.author %}"
              > {{ comment.author }} </a>
            </h5>
            <p> {{ comment.text }} </p>
          </div>
        </div>
      {% endfor%}
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
  Профиль пользователя {{ author.get_full_name }}
{% endblock %}
{% block content %}
  <div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ number_of_posts }} </h3>
    {% if request.user.is_authenticated %}
        {% if request.user != author %}
          {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
            Отписаться
          </a>
          {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
         </a>
        {% endif %}
      {% endif %}
    {% endif %}
    {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ author.username }}
        </li>
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li>
          Дата публикации: {{post.pub_date|date:"j E Y"}}
        </li>
      </ul>
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация </a>
      {% if post.group is not None %}      
        <a href="{% url 'posts:group_posts' post.group.slug %}">Все посты группы</a> 
      {% endif %}       
    {% if not forloop.last %}<hr>{% endif %}
    </article>
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}    
  </div>
{% endblock %}

yatube/templates/posts/profile3.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {{ author.username }}{% endblock %}
{% block content %}
{% load thumbnail %}
  <div class="container py-5">
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.username }}</h1>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% if request.user != author %}
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
   {% endif %}
  </div>
      {% for post in page_obj %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }} 
        </p>
        {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать пост
          </a><br>
        {% endif %}
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    {% if post.group %}
      <br>
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> 
    {% endif %}       
    <hr>
    <article>
    {% endfor %}  
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %} 